dist: bionic
os: linux

git:
    submodules: false

jobs:
  include:
  - name: unittest
    script:
    - python3 -m unittest src/report.py
    - python3 -m doctest  src/gtest.py
#~
# GCC
#~
  - name: gcc [no omp]
    compiler: gcc
    env: 
      - CXX='g++-10'
      - CXXFLAGS='-Wall -Wextra -Werror -Wno-unknown-pragmas'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-10 
        - python3
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed

  - name: gcc [no omp full]
    compiler: gcc
    env: 
      - CXX='g++-10'
      - CXXFLAGS='-Wall -Wextra -Werror -Wno-unknown-pragmas'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-10 
        - python3
    install:
    - pip install -r requirements.txt
    script:
    - ./ovo.sh gen tiers 3
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed

  - name: gcc [omp]
    compiler: gcc
    env:
      - CXX='g++-10'
      - CXXFLAGS='-Wall -Wextra -Werror -Wno-unknown-pragmas -fopenmp -foffload=disable'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-10
        - python3
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed || true

#~
# icx
#~

  - name: icx [omp offload host]
    compiler: icx
    env:
      - CXX='icx'
      - CXXFLAGS='-Wall -Wextra -Werror -Wno-unknown-pragmas -fiopenmp -fopenmp-targets=x86_64-pc-linux-gnu -fopenmp-version=50'
      - OVO_TIMEOUT='3m'
    addons:
      apt:
        sources:
        - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
          key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        packages:
        - intel-oneapi-icc
        - python3
    install:
    - source /opt/intel/inteloneapi/compiler/latest/env/vars.sh
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed || true

#~
# gfortran
#~

  - name: gfortran [no omp]
    compiler: gfortran
    env: 
      - FC='gfortran-10 -Wall -Wextra -Werror'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - gfortran-10
        - python3
    script:
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report --failed

  - name: gfortran [no omp full]
    compiler: gfortran
    env: 
      - FC='gfortran-9 -Wall -Wextra -Werror'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - gfortran-9 
        - python3
    install:
    - pip install -r requirements.txt
    script:
    - ./ovo.sh gen tiers 3
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report --failed

#~
# ifx
#~

  - name: ifx [omp offload host full]
    compiler: ifx
    env:
      - FC='ifx'
      - FFLAGS='-fiopenmp -fopenmp-targets=x86_64-pc-linux-gnu -fopenmp-version=50'
      - OVO_TIMEOUT='3m'
    addons:
      apt:
        sources:
        - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
          key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        packages:
        - intel-oneapi-ifort
        - python3
    install:
    - source /opt/intel/inteloneapi/compiler/latest/env/vars.sh
    script:
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report --failed || true
